//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_soruce_mil
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestPurchase
    {
        public byte id { get; set; }
        public string type { get; set; }
        public string brand { get; set; }
        public string color { get; set; }
        public string size { get; set; }
        public Nullable<decimal> price { get; set; }
        public string url { get; set; }
        public Nullable<byte> postnr { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string name { get; set; }
        public string comment { get; set; }
    }
}
